project:
  type: book

book:
  title: "Mehanika Fluida 1 - Skripta za vježbe"
  author: "Vaše Ime/Sveučilište"
  date: "2026-03-12"
  chapters:
    - index.qmd
    - part: "Vježbe"
      chapters:
        - vjezba_01.qmd
        - vjezba_02.qmd
        - vjezba_03.qmd
        - vjezba_04.qmd
        - vjezba_05.qmd
        - vjezba_06.qmd
        - vjezba_07.qmd
        - vjezba_08.qmd
        - vjezba_09.qmd
        - vjezba_10.qmd
        - vjezba_11.qmd
        - vjezba_12.qmd
        - vjezba_13.qmd

format:
  html:
    theme: cosmo
    css: custom.css
    toc: false
    number-sections: true
    code-fold: true

editor: visual
