project:
  type: website

website:
  title: "Mehanika Fluida 1 - Skripta za vježbe"
  page-navigation: true
  sidebar:
    style: "docked"
    contents:
      - text: "Predgovor"
        href: index.qmd
      - section: "Vježbe"
        contents:
          - text: "1 — Uvod i Pascalov zakon"
            href: vjezba_01.qmd
          - text: "2 — Viskoznost"
            href: vjezba_02.qmd
          - text: "3 — Statika fluida"
            href: vjezba_03.qmd
          - text: "4 — Relativno mirovanje"
            href: vjezba_04.qmd
          - text: "5 — Ravne plohe"
            href: vjezba_05.qmd
          - text: "6 — Zakrivljene plohe 1"
            href: vjezba_06.qmd
          - text: "7 — Zakrivljene plohe 2"
            href: vjezba_07.qmd
          - text: "8 — Kontinuitet"
            href: vjezba_08.qmd
          - text: "9 — Idealni Bernoulli"
            href: vjezba_09.qmd
          - text: "10 — Realni Bernoulli"
            href: vjezba_10.qmd
          - text: "11 — Impuls 1"
            href: vjezba_11.qmd
          - text: "12 — Impuls 2"
            href: vjezba_12.qmd
          - text: "13 — Cjevovodi"
            href: vjezba_13.qmd

format:
  html:
    theme: flatly
    css: custom.css
    toc: false
    number-sections: false
    code-fold: false

editor: visual
