project:
  type: book

book:
  title: "Naziv kolegija - Online skripta"
  author: "Ime nastavnika / institucija"
  date: "2026-04-01"
  chapters:
    - index.qmd
    - part: "Teme"
      chapters:
        - tema_01.qmd
        - tema_02.qmd
        - tema_03.qmd

format:
  html:
    theme: cosmo
    css: custom.css
    toc: false
    number-sections: true
    code-fold: true
    lang: hr

editor: visual
